from car import  Car,ElectricCar
car1 = Car('Maruti', '800', 1992)
car1.describe_car()
car1.read_odometer()
car1.update_odometer(40)
car1.read_odometer()
car1.update_odometer(10)
car1.update_odometer(50)
car1.read_odometer()
print(f"The {car1.make} {car1.model} has completed {car1.display_trips()} trips.")
print(f"The {car1.car_name()} has completed {car1.display_trips()} trips.")
car1.update_odometer(-20)
car1.read_odometer()
print(f"The {car1.make} {car1.model} has completed {car1.display_trips()} trips.")
print(f"The {car1.car_name()} has completed {car1.display_trips()} trips.")

car2 = Car('Maruti', '800', 1992)
e_car = ElectricCar('Tata', 'Nexon', 2022)
e_car.describe_car()